//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    #region "Order"
    public partial class Order
    {
        public short Order_Id { get; set; }
        [DataType(DataType.Date)]
        [Display(Name ="Order Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime OrderDate { get; set; }
        public short User_Id { get; set; }
        public int ISBM { get; set; }
    
        public virtual BookDetail BookDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
    #endregion
}
